# Host 1
FROM alpine:latest AS host_kzouggar-1
COPY _kzouggar-1.sh /_kzouggar-1.sh
RUN chmod +x /_kzouggar-1.sh
CMD ./_kzouggar-1.sh

# Host 2
FROM alpine:latest AS host_kzouggar-2
COPY _kzouggar-2.sh /_kzouggar-2.sh
RUN chmod +x /_kzouggar-2.sh
CMD ./_kzouggar-2.sh

# Routeur 1
FROM frrouting/frr AS routeur_kzouggar-1
COPY _kzouggar-1_s.sh /_kzouggar-1_s.sh
COPY _kzouggar-1_g.sh /_kzouggar-1_g.sh
RUN chmod +x /_kzouggar-1_s.sh /_kzouggar-1_g.sh
CMD ./_kzouggar-1_s.sh

# Routeur 2
FROM frrouting/frr AS routeur_kzouggar-2
COPY _kzouggar-2_s.sh /_kzouggar-2_s.sh
COPY _kzouggar-2_g.sh /_kzouggar-2_g.sh
RUN chmod +x /_kzouggar-2_s.sh /_kzouggar-2_g.sh
CMD ./_kzouggar-2_s.sh
 