# Host 1
FROM issamelferkh/host_iel-ferk:1.0 AS host_iel-ferk-1

# Host 2
FROM issamelferkh/host_iel-ferk:1.0 AS host_iel-ferk-2

# Host 3
FROM issamelferkh/host_iel-ferk:1.0 AS host_iel-ferk-3

# Router 1
FROM issamelferkh/routeur_iel-ferk:1.0 AS routeur_iel-ferk-1
COPY router_iel-ferk-1.sh /router_iel-ferk-1.sh
RUN chmod +x router_iel-ferk-1.sh
CMD ./router_iel-ferk-1.sh

# Router 2
FROM issamelferkh/routeur_iel-ferk:1.0 AS routeur_iel-ferk-2
COPY router_iel-ferk-2.sh /router_iel-ferk-2.sh
RUN chmod +x router_iel-ferk-2.sh
CMD ./router_iel-ferk-2.sh

# Router 3
FROM issamelferkh/routeur_iel-ferk:1.0 AS routeur_iel-ferk-3
COPY router_iel-ferk-3.sh /router_iel-ferk-3.sh
RUN chmod +x router_iel-ferk-3.sh
CMD ./router_iel-ferk-3.sh

# Router 4
FROM issamelferkh/routeur_iel-ferk:1.0 AS routeur_iel-ferk-4
COPY router_iel-ferk-4.sh /router_iel-ferk-4.sh
RUN chmod +x router_iel-ferk-4.sh
CMD ./router_iel-ferk-4.sh
